name: ActivaPYME
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40726286522112787
title: ERP en la nube
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9426671334076673
  lightness: 0.2935030844528228
  saturation: 0.43963737040758133
  rhythmicContrast: 0.5546852794941515
purpose: []
