name: ActivaPYME
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40726286522112787
title: ERP en la nube
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e48020'
    - '#de0808'
    - '#f4c10d'
    - '#000000'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 0.2935030844528228
  saturation: 0.43963737040758133
  rhythmicContrast: 0.5546852794941515
purpose: []
